COPY ~questpack/encounters/ding0/randenc/d0ogrema.cre~ ~override~
     ~questpack/encounters/ding0/randenc/d0bohun1.cre~ ~override~
     ~questpack/encounters/ding0/randenc/d0bohun2.cre~ ~override~

COPY_EXISTING ~ORC01.CRE~ ~override/d0qpsy01.cre~
              ~ORC02.CRE~ ~override/d0qpsy02.cre~
              ~HOBELI01.CRE~ ~override/d0qpsy03.cre~
              ~ICGOB01.CRE~ ~override/d0qpsy04.cre~
              ~OGRE01.CRE~ ~override/d0qpsy05.cre~
              ~KOBARC01.CRE~ ~override/d0qpsy06.cre~
              ~OGRILL01.CRE~ ~override/d0qpsy07.cre~
              ~GNLELI01.CRE~ ~override/d0qpsy08.cre~
              ~ICMIN01.CRE~ ~override/d0qpsy09.cre~
              ~PLSHFG01.CRE~ ~override/d0qpsy10.cre~
  SAY NAME1 @304 // Sythillisian Soldier
  SAY NAME2 @304 // Sythillisian Soldier

EXTEND_BOTTOM ~ar0041.bcs~ ~questpack/encounters/ding0/randenc/city_old.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ar0045.bcs~ ~questpack/encounters/ding0/randenc/city_old.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ar0046.bcs~ ~questpack/encounters/ding0/randenc/city_old.baf~ EVALUATE_BUFFER

COPY_EXISTING ~ar0041.bcs~ ~override~
              ~ar0045.bcs~ ~override~
              ~ar0046.bcs~ ~override~
  REPLACE_BCS_BLOCK EVALUATE_BUFFER ~questpack/encounters/ding0/randenc/city_old.baf~
                    ~questpack/encounters/ding0/randenc/city_new.baf~
BUT_ONLY

EXTEND_BOTTOM ~ar0042.bcs~ ~questpack/encounters/ding0/randenc/wilderness_old.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ar0043.bcs~ ~questpack/encounters/ding0/randenc/wilderness_old.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ar0044.bcs~ ~questpack/encounters/ding0/randenc/wilderness_old.baf~ EVALUATE_BUFFER

COPY_EXISTING ~ar0042.bcs~ ~override~
              ~ar0043.bcs~ ~override~
              ~ar0044.bcs~ ~override~
  REPLACE_BCS_BLOCK EVALUATE_BUFFER ~questpack/encounters/ding0/randenc/wilderness_old.baf~
                    ~questpack/encounters/ding0/randenc/wilderness_new.baf~
BUT_ONLY
