COPY_EXISTING ~DEMOSUM1.CRE~ ~override/d0qpwima.cre~ // Marilith
  SAY NAME1 @268
  SAY NAME2 @268
  SAY INITIAL_MEETING #61758
  WRITE_ASCII 0x248 "d0qpwima" #8
  WRITE_ASCII 0x2cc "d0qpwima" #8
  WRITE_ASCII 0x280 "d0qpwima" #32
  WRITE_BYTE 0x270 128

COPY_EXISTING ~DEMOSUM1.CRE~ ~override/d0qpwigi.cre~ // Girl
  SAY NAME1 #9406
  SAY NAME2 #9406
  SAY INITIAL_MEETING #-1
  WRITE_SHORT 0x28 50960
  WRITE_ASCII 0x2cc "d0qpwigi" #8
  WRITE_BYTE 0x270 128
  WRITE_ASCII 0x248 "d0qpwigi" #8
  WRITE_ASCII 0x250 "" #8
  WRITE_ASCII 0x258 "" #8
  WRITE_ASCII 0x260 "" #8
  WRITE_ASCII 0x268 "" #8
  WRITE_ASCII 0x280 "d0qpwigi" #32

COPY ~questpack/wilbur/d0qpwisw.itm~ ~override~
  SAY NAME2 @301
  SAY IDENTIFIED_DESC @302

COPY ~questpack/wilbur/d0qpwiwi.cre~ ~override~
     ~questpack/wilbur/d0qpwiw2.cre~ ~override~
  SAY NAME1 @303
  SAY NAME2 @303

COPY ~questpack/wilbur/d0qpwiwi.sto~ ~override~
  SAY 0xc @303

COPY ~questpack/wilbur/d0qpwic1.cre~ ~override~
     ~questpack/wilbur/d0qpwic2.cre~ ~override~
     ~questpack/wilbur/d0qpwii1.cre~ ~override~
     ~questpack/wilbur/d0qpwii2.cre~ ~override~
     ~questpack/wilbur/d0qpwisw.bam~ ~override~

COMPILE EVALUATE_BUFFER ~questpack/wilbur/dialog.d~ USING
        ~%tra_path%/english/wilbur.tra~
        ~%tra_path%/%LANGUAGE%/wilbur.tra~

ADD_JOURNAL @21 @23 @26 USING
            ~%tra_path%/english/wilbur.tra~
            ~%tra_path%/%LANGUAGE%/wilbur.tra~

COMPILE EVALUATE_BUFFER ~questpack/wilbur/d0qpwigi.baf~
        ~questpack/wilbur/d0qpwima.baf~
        ~questpack/wilbur/d0qpwiwi.baf~
        ~questpack/wilbur/d0qpwiw2.baf~
        ~questpack/wilbur/d0qpwic1.baf~
        ~questpack/wilbur/d0qpwic2.baf~
        ~questpack/wilbur/d0qpwii1.baf~
        ~questpack/wilbur/d0qpwii2.baf~

EXTEND_BOTTOM ~ar0500.bcs~ ~questpack/wilbur/et_0500.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~ar0502.bcs~ ~questpack/wilbur/et_0502.baf~ EVALUATE_BUFFER

COPY_EXISTING ~ar0530.are~ ~override~
  WRITE_ASCII 0x94 "ar0530" #8
BUT_ONLY

EXTEND_TOP ~ar0530.bcs~ ~questpack/wilbur/ar0530.baf~ EVALUATE_BUFFER

COPY ~questpack/wilbur/d0nosnd.wav~ ~override~
